-- veiw tables
select * from bugs
select * from reporters

--delete tables
DROP TABLE bugs;
DROP TABLE reporters;

-- bug table
CREATE TABLE bugs (
    bug_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL UNIQUE,
    description VARCHAR2(1000) NOT NULL,
    artifact_type VARCHAR2(100),
    status VARCHAR2(50),
    priority VARCHAR2(50),

    reported_by VARCHAR2(100),  -- stores reporter_id (email)

    date_found DATE DEFAULT SYSDATE,
    date_fixed DATE,

    CONSTRAINT fk_reporter
        FOREIGN KEY (reported_by)
        REFERENCES reporters(reporter_id)
);

-- make reporter not null
ALTER TABLE bugs
MODIFY reported_by CONSTRAINT nn_reported_by NOT NULL;

-- reporter table
CREATE TABLE reporters (
    reporter_id VARCHAR2(100) PRIMARY KEY,  -- e.g. email
    name VARCHAR2(100) NOT NULL,
    role VARCHAR2(50) NOT NULL
);
-- insert into reporter table
INSERT INTO system.reporters (reporter_id, name, role) VALUES ('aisha@test.com', 'Aisha Khan', 'Tester');
INSERT INTO system.reporters (reporter_id, name, role) VALUES ('daniel@dev.com', 'Daniel Lee', 'Developer');
INSERT INTO system.reporters (reporter_id, name, role) VALUES ('sofia@client.com', 'Sofia Martinez', 'Customer');
INSERT INTO system.reporters (reporter_id, name, role) VALUES ('ethan@test.com', 'Ethan Patel', 'Tester');
INSERT INTO system.reporters (reporter_id, name, role) VALUES ('maya@dev.com', 'Maya Chen', 'Developer');
INSERT INTO system.reporters (reporter_id, name, role) VALUES ('liam@client.com', 'Liam O''Connor', 'Customer');
INSERT INTO system.reporters (reporter_id, name, role) VALUES ('noah@test.com', 'Noah Ibrahim', 'Tester');
INSERT INTO system.reporters (reporter_id, name, role) VALUES ('olivia@dev.com', 'Olivia Rossi', 'Developer');

--commit to db
COMMIT;